import React, { useState, useEffect } from "react";
import { useFocus } from "../context/FocusContext";
import { useNavigate } from "react-router-dom";
import { apiGenerateAIPunishment, apiVerifyAIPunishment } from "../api/prodoApi";
import type { AIPunishmentTask } from "../api/prodoApi";

/**
 * Cognitive Punishment Node Page.
 * Displayed when user XP balance is negative.
 * Fetches AI-generated whimsical and annoying punishment tasks generated by Gemini / Groq.
 */
const PunishmentsPage: React.FC = () => {
  const { xp, adjustXp, setIsAuthenticated, stopTracking } = useFocus();
  const navigate = useNavigate();

  const [task, setTask] = useState<AIPunishmentTask | null>(null);
  const [loadingTask, setLoadingTask] = useState<boolean>(true);
  const [userAnswer, setUserAnswer] = useState<string>("");
  const [selectedOption, setSelectedOption] = useState<string>("");
  const [statusMsg, setStatusMsg] = useState<string | null>(null);
  const [isVerifying, setIsVerifying] = useState<boolean>(false);

  const fetchAITask = async () => {
    setLoadingTask(true);
    setStatusMsg(null);
    setUserAnswer("");
    setSelectedOption("");
    try {
      const res = await apiGenerateAIPunishment();
      if (res.success && res.task) {
        setTask(res.task);
      }
    } catch (err: any) {
      console.error("Failed to generate AI task:", err);
      setStatusMsg("❌ AI_GEN_FAIL: Could not fetch enforcer task. Retrying...");
    } finally {
      setLoadingTask(false);
    }
  };

  useEffect(() => {
    fetchAITask();
  }, []);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!task) return;

    const answerToTest = task.task_type === "MULTIPLE_CHOICE" ? selectedOption : userAnswer;
    if (!answerToTest) {
      setStatusMsg("⚠️ Please enter or select an answer before verifying.");
      return;
    }

    setIsVerifying(true);
    setStatusMsg(null);

    try {
      const res = await apiVerifyAIPunishment(answerToTest, task.correct_answer);
      if (res.success) {
        setStatusMsg("✓ COGNITIVE_AUTHORITY_RESTORED: +250 XP awarded!");
        adjustXp(250);
        setTimeout(() => {
          navigate("/focus");
        }, 1500);
      } else {
        setStatusMsg(res.message || "❌ VERIFICATION_FAIL: Incorrect solution. Try again.");
      }
    } catch (err: any) {
      setStatusMsg(`❌ Error: ${err.message}`);
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="w-screen h-screen bg-[#0A0A0A] text-on-surface flex items-center justify-center font-log-body p-6 select-none z-[9999] absolute inset-0">
      <div className="w-full max-w-2xl border-2 border-crimson bg-surface-container-lowest flex flex-col shadow-2xl">
        
        {/* Header Warning */}
        <div className="border-b border-crimson bg-[#1C0000] px-6 py-3 flex justify-between items-center text-xs font-technical-prefix text-crimson">
          <span className="blink-cursor font-bold">⚠️ SYSTEM_LOCKDOWN_ACTIVE</span>
          <span className="font-bold">NEGATIVE_BALANCE: {xp} XP</span>
        </div>

        <div className="p-6 flex flex-col gap-6">
          
          <div className="flex justify-between items-start border-b border-surface-variant pb-4">
            <div>
              <h1 className="font-value-lg text-[28px] text-crimson uppercase tracking-wider">
                COGNITIVE PUNISHMENT NODE
              </h1>
              <p className="font-technical-prefix text-[10px] text-outline-variant uppercase mt-1">
                AI-ENFORCED COGNITIVE PUNISHMENT PROTOCOL
              </p>
            </div>
            
            {task?.provider_used && (
              <span className="bg-amber/10 border border-amber/30 text-amber text-[9px] font-technical-prefix font-bold uppercase px-2.5 py-1">
                AI ENGINE: {task.provider_used}
              </span>
            )}
          </div>

          {loadingTask ? (
            <div className="py-12 flex flex-col items-center gap-3 text-center">
              <span className="material-symbols-outlined text-[48px] text-amber animate-spin">smart_toy</span>
              <div className="font-technical-prefix text-xs text-amber font-bold uppercase animate-pulse">
                GENERATING WHIMSICAL ENFORCER TASK VIA AI...
              </div>
            </div>
          ) : !task ? (
            <div className="py-8 text-center text-crimson font-technical-prefix text-xs uppercase">
              Failed to load AI task.
              <button onClick={fetchAITask} className="ml-2 underline text-amber">Retry</button>
            </div>
          ) : (
            <form onSubmit={handleVerify} className="flex flex-col gap-5">
              
              {/* Task Title & Description */}
              <div className="bg-background border border-outline-variant p-4 flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-crimson animate-ping"></span>
                  <span className="font-technical-prefix text-xs text-crimson font-bold uppercase">
                    {task.title}
                  </span>
                </div>
                <p className="font-technical-prefix text-[11px] text-outline-variant uppercase leading-relaxed">
                  {task.description}
                </p>
              </div>

              {/* Task Prompt Box */}
              <div className="bg-surface-container-high border border-amber/40 p-4 text-xs font-technical-prefix text-amber leading-relaxed">
                &gt; PROMPT: {task.prompt}
              </div>

              {/* Input Control according to task_type */}
              {task.task_type === "MULTIPLE_CHOICE" && task.options && (
                <div className="flex flex-col gap-2">
                  <span className="font-technical-prefix text-[9px] text-outline-variant uppercase">SELECT CORRECT ANSWER:</span>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {task.options.map((opt, idx) => (
                      <button
                        key={idx}
                        type="button"
                        onClick={() => setSelectedOption(opt)}
                        className={`p-3 border font-technical-prefix text-xs text-left uppercase transition-all ${
                          selectedOption === opt
                            ? "bg-amber/20 border-amber text-amber font-bold shadow-md"
                            : "bg-background border-outline-variant hover:border-primary text-on-surface"
                        }`}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {task.task_type === "TYPING_PLEDGE" && (
                <div className="flex flex-col gap-2">
                  <span className="font-technical-prefix text-[9px] text-outline-variant uppercase">TYPE PLEDGE EXACTLY:</span>
                  <textarea
                    rows={3}
                    value={userAnswer}
                    onChange={(e) => setUserAnswer(e.target.value)}
                    placeholder="Type pledge here..."
                    className="w-full bg-background border border-outline-variant p-3 font-technical-prefix text-xs text-primary outline-none focus:border-amber"
                  />
                </div>
              )}

              {task.task_type === "RIDDLE" && (
                <div className="flex flex-col gap-2">
                  <span className="font-technical-prefix text-[9px] text-outline-variant uppercase">ENTER SOLUTION:</span>
                  <input
                    type="text"
                    value={userAnswer}
                    onChange={(e) => setUserAnswer(e.target.value)}
                    placeholder="Enter answer (e.g. 28)"
                    className="w-full max-w-xs bg-background border border-outline-variant p-3 font-technical-prefix text-xs text-primary outline-none focus:border-amber text-center"
                  />
                </div>
              )}

              {/* Status Message */}
              {statusMsg && (
                <div className="font-technical-prefix text-xs uppercase p-3 bg-surface-container-high border border-outline-variant">
                  {statusMsg}
                </div>
              )}

              {/* Actions */}
              <div className="flex justify-between items-center pt-2">
                <button
                  type="button"
                  onClick={fetchAITask}
                  className="py-2 px-3 border border-outline-variant hover:border-amber text-amber font-technical-prefix text-[10px] uppercase font-bold flex items-center gap-1"
                >
                  <span className="material-symbols-outlined text-[14px]">refresh</span>
                  Generate New Whimsical Task
                </button>

                <button
                  type="submit"
                  disabled={isVerifying}
                  className="py-2.5 px-6 bg-emerald text-background hover:bg-green-400 font-technical-prefix text-xs font-bold uppercase transition-all shadow-lg"
                >
                  {isVerifying ? "Verifying..." : "Submit & Restore Authority (+250 XP)"}
                </button>
              </div>

            </form>
          )}

          {/* Reset / Logout Session */}
          <div className="border-t border-surface-variant pt-4 mt-2 flex justify-end">
            <button
              type="button"
              onClick={() => {
                localStorage.removeItem("prodo_token");
                sessionStorage.removeItem("prodo_token");
                setIsAuthenticated(false);
                stopTracking();
                navigate("/login");
              }}
              className="px-4 py-2 border border-crimson/50 hover:bg-crimson/10 font-technical-prefix text-[10px] uppercase text-crimson font-bold transition-all"
            >
              Logout / Reset Session
            </button>
          </div>

        </div>
      </div>
    </div>
  );
};

export default PunishmentsPage;
